---
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: theskibiditeca_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: Developer
      MSSQL_COLLATION: "Latin1_General_100_CI_AS_SC_UTF8"
    volumes:
      - sqlserver_data:/var/opt/mssql
    expose:
      - "1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "$SA_PASSWORD", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 10s
  app:
    build:
      context: .
      dockerfile: TheSkibiditeca.Web/Dockerfile
    image: theskibiditeca_app:latest
    ports:
      - "9090:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=TheSkibiditeca;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=true;
      - RUN_MIGRATIONS=true
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/Health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
volumes:
  sqlserver_data:
