// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheSkibiditeca.Web.Data;

#nullable disable

namespace TheSkibiditeca.Web.Migrations.Npgsql
{
    [DbContext(typeof(DbContextPostgres))]
    [Migration("20250817204024_DropLoanReservationBookAssociation")]
    partial class DropLoanReservationBookAssociation
    {
        /// <summary>
        /// Builds the target EF Core model used by this migration.
        /// </summary>
        /// <param name="modelBuilder">The <see cref="ModelBuilder"/> to configure the model with.</param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // minimal designer to satisfy EF Core tooling
        }
    }
}
